---
- hosts: 127.0.0.1
  connection: local

- tasks:
  
  - name: Install Chocolatey
    win_shell: "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

  - name: Ensure Chocolatey itself is installed and use internal repo as source
    win_chocolatey:
        name: chocolatey
        source: http://someserver/chocolatey

  - name: Install Browsers
    tags: [browser]
    win_chocolatey:
      name:
      - firefox
      - brave

  - name: Install System Tools
    tags: [systools]
    win_chocolatey:
      name:
      - openssh
      - sysinternals
      - 7zip
      - nxlog
      - nmap
      - wireshark
      - osquery
      - pstools

  - name: Install Productivity Software
    tags: [productivity]
    win_chocolatey:
      name:
      - mobaxterm
      - alacritty
      - doublecmd
      - marktext
      - neovim
      - notable
      - pandoc
      - gnupg
      - gpg4win
      - gopass
      - qtpass
      state: present

  - name: Install Programming Languages
    tags: [programming]
    win_chocolatey:
      name:
      - python
      - nodejs.install
      - qtcreator
      - golang
      - julia
      - visualstudio2019community

  - name: Install Development Tools
    tags: [development]
    win_chocolatey:
      name:
      - jq
      - cmake
      - dbeaver
      - git.install
      - gitea
      - insomnia-rest-api-client
      - pycharm
      - pypy3
      - pyqt5

  - name: Install Cloud Tools
    tags: [cloud]
    win_chocolatey:
      name:
      - cloudfoundry-cli
      - docker-cli
      - docker-desktop
      - dive
      - ctop
      - vagrant
      - vagrant-manager
      - qemu

  - name: Install Science Applications
    tags: [science]
    win_chocolatey:
      name:
        - miktex
        - latexdraw
        - nteract
        - texstudio
        - r.project
        - r.studio

  - name: Install Creativity / Multimedia
    tags: [creative]
    win_chocolatey:
      name:
        - digikam
        - blender
        - audacity
        - audacity-lame
        - audacity-ffmpeg
        - imagemagick
  
  - name: Install Making Tools
    tags: [make]
    win_chocolatey:
      name:
      - freecad
      - kicad
      - vscode-arduino
      - fritzing
